import type { Metadata } from "next";
import { LegalPage, LegalSection } from "@/components/legal/legal-page";

export const metadata: Metadata = {
  title: "Disclaimer",
  description:
    "Important disclaimers for PrayNote AI — faith tool, not medical, legal, or professional advice. From Eternal Faith.",
};

const UPDATED = "July 10, 2026";

export default function DisclaimerPage() {
  return (
    <LegalPage
      title="Disclaimer"
      description="Please read this carefully. PrayNote is a spiritual journaling tool — not a substitute for pastoral care, medicine, or professional advice."
      updated={UPDATED}
    >
      <LegalSection title="1. Nature of the service">
        <p>
          PrayNote AI is a software tool that helps users journal prayer, browse
          Scripture, and receive automated suggestions (including AI-assisted
          categories and Bible verse ideas). It is provided by the Eternal Faith
          team for personal spiritual use.
        </p>
        <p>
          It is <strong>not</strong> a church, denomination, licensed counseling
          service, medical service, or emergency service.
        </p>
      </LegalSection>

      <LegalSection title="2. Not medical, mental health, or crisis care">
        <p>
          Content in the app — including AI responses, devotionals, and verse
          suggestions — is <strong>not medical advice</strong>, diagnosis, or
          treatment, and is not a substitute for licensed mental health care.
        </p>
        <p>
          If you are in crisis, considering self-harm, or in danger, contact
          local emergency services or a crisis hotline immediately. Do not rely
          on this app for emergency help.
        </p>
      </LegalSection>

      <LegalSection title="3. Not legal, financial, or professional advice">
        <p>
          Nothing on PrayNote constitutes legal, financial, tax, or other
          professional advice. Make important decisions with qualified
          professionals and, where appropriate, your local church leaders.
        </p>
      </LegalSection>

      <LegalSection title="4. Scripture and theology">
        <p>
          Bible text may come from public-domain or licensed sources (e.g. KJV
          and other translations when configured). AI may suggest verse
          references; we try to resolve passage text from Bible APIs, but{" "}
          <strong>errors or imperfect matches can occur</strong>.
        </p>
        <p>
          AI “reasons,” categories, and encouragements are generated by models
          and may be incomplete, biased, or theologically imperfect. Always
          test teaching against Scripture itself and wise pastoral counsel.
          PrayNote does not claim infallibility or divine revelation through AI.
        </p>
      </LegalSection>

      <LegalSection title="5. AI limitations">
        <ul className="list-disc space-y-1 pl-5">
          <li>AI can misunderstand context or tone of a prayer.</li>
          <li>AI can suggest irrelevant or imperfect verse links.</li>
          <li>AI must not be treated as a pastor, prophet, or therapist.</li>
          <li>
            Features may be rate-limited, changed, or unavailable without
            notice.
          </li>
        </ul>
      </LegalSection>

      <LegalSection title="6. No guarantee of outcomes">
        <p>
          We do not guarantee spiritual outcomes, answered prayer results,
          uptime, accuracy of content, or fitness for a particular purpose. The
          service is provided <strong>“as is” and “as available.”</strong>
        </p>
      </LegalSection>

      <LegalSection title="7. User responsibility">
        <p>You are responsible for:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>How you use and interpret content in the app.</li>
          <li>Keeping your account credentials secure.</li>
          <li>
            Not uploading unlawful content or abusing AI, voice, or APIs.
          </li>
          <li>
            Confirming any verse or teaching with a trusted Bible and community.
          </li>
        </ul>
      </LegalSection>

      <LegalSection title="8. Third-party services">
        <p>
          Hosting, auth, AI, email, and Bible APIs are provided by third parties.
          We are not responsible for their outages, policy changes, or errors
          beyond our reasonable control. Their terms also apply to their
          processing of data.
        </p>
      </LegalSection>

      <LegalSection title="9. Limitation of liability">
        <p>
          To the maximum extent permitted by law, the Eternal Faith team and
          PrayNote operators are not liable for any indirect, incidental,
          special, consequential, or punitive damages, or any loss of data,
          profits, or spiritual opportunity arising from your use of the service.
          Where liability cannot be excluded, it is limited to the greater of
          (a) fees you paid us for the service in the prior three months, or
          (b) USD $50, if free.
        </p>
        <p className="text-xs text-[oklch(0.5_0.03_255)]">
          Some jurisdictions do not allow certain limitations; in those places,
          limits apply only to the extent allowed.
        </p>
      </LegalSection>

      <LegalSection title="10. Faith community note">
        <p>
          We hope PrayNote helps you pray with the Word. Technology is a tool;
          Jesus Christ is Lord. Use this app as a help — never as a replacement
          for Scripture, prayer, fellowship, or the local church.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
